apiVersion: v1
kind: PersistentVolume
metadata:
  name: mypv2
  namespace: ingress-nginx
spec:
  capacity:
    storage: 80Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath: 
    path: /data/mongo

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: mypv3
  namespace: ingress-nginx
spec:
  capacity:
    storage: 80Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath: 
    path: /data/mongo


--- 

apiVersion: v1
kind: PersistentVolume
metadata:
  name: mypv4
  namespace: ingress-nginx
spec:
  capacity:
    storage: 80Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath: 
    path: /data/mongo

