apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo-dep
spec:
  selector:
    matchLabels:
      app: mongo-dep
  template:
    metadata:
      labels:
        app: mongo-dep
    spec:
      containers:
      - name: mongo
        image: mongo
        volumeMounts: 
          - name: mongopv
            mountPath: /data/whatever
        env:
          - name: MONGO_INITDB_ROOT_USERNAME
            valueFrom: 
              secretKeyRef: 
                name: mongosecret
                key: MONGO_INITDB_ROOT_USERNAME
          - name: MONGO_INITDB_ROOT_PASSWORD
            valueFrom: 
              secretKeyRef: 
                name: mongosecret
                key: MONGO_INITDB_ROOT_PASSWORD

        ports:
        - containerPort: 27017

      volumes: 
      - name: mongopv
        persistentVolumeClaim: 
          claimName: mypvc2
