apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongoexpress
spec:
  selector:
    matchLabels:
      app: mongoexpress
  template:
    metadata:
      labels:
        app: mongoexpress
    spec:
      containers:
      - name: mongoexpress
        image: mongo-express
        env:
          - name: ME_CONFIG_MONGODB_SERVER
            value: mongo
          - name: ME_CONFIG_MONGODB_ADMINUSERNAME
            valueFrom:
              secretKeyRef:
                name: mongoexpresssecret
                key: ME_CONFIG_MONGODB_ADMINUSERNAME
          - name: ME_CONFIG_MONGODB_ADMINPASSWORD
            valueFrom:
              secretKeyRef:
                name: mongoexpresssecret
                key: ME_CONFIG_MONGODB_ADMINPASSWORD
          - name: ME_CONFIG_BASICAUTH
            value: "false"
          # - name: ME_CONFIG_MONGODB_URL
          #   value: mongodb://root:password@mongo:27017/
        ports:
        - containerPort: 8081
